/**
 * Brand → base-model dictionary for catalog filters and listing forms.
 *
 * Listings store specific trim names like "X5 xDrive30d" or "320d F30".
 * Filtering uses startsWith() against the base model, so picking "X5" matches
 * "X5 xDrive30d", "X5 M50i", etc.
 *
 * Spellings of pre-existing brands ("VW", "Mercedes", "Škoda", "Citroën")
 * are kept as-is so older listings and saved filters keep matching.
 */

export const BRANDS: string[] = [
  "Abarth",
  "Alfa Romeo",
  "Alpine",
  "Aston Martin",
  "Audi",
  "Bentley",
  "BMW",
  "BYD",
  "Cadillac",
  "Chevrolet",
  "Chrysler",
  "Citroën",
  "Cupra",
  "Dacia",
  "Daewoo",
  "Dodge",
  "DS",
  "Ferrari",
  "Fiat",
  "Ford",
  "Genesis",
  "Honda",
  "Hyundai",
  "Infiniti",
  "Jaguar",
  "Jeep",
  "Kia",
  "Lada",
  "Lamborghini",
  "Lancia",
  "Land Rover",
  "Lexus",
  "Lotus",
  "Maserati",
  "Mazda",
  "McLaren",
  "Mercedes",
  "MG",
  "Mini",
  "Mitsubishi",
  "Nissan",
  "Opel",
  "Peugeot",
  "Polestar",
  "Porsche",
  "Renault",
  "Rolls-Royce",
  "Saab",
  "Seat",
  "Škoda",
  "Smart",
  "SsangYong",
  "Subaru",
  "Suzuki",
  "Tesla",
  "Toyota",
  "VW",
  "Volvo",
  "ZAZ",
];

export const MODELS_BY_BRAND: Record<string, string[]> = {
  Abarth: ["500", "500e", "595", "695", "124 Spider", "Grande Punto", "Punto Evo"],
  "Alfa Romeo": ["MiTo", "Giulietta", "Giulia", "Stelvio", "Tonale", "159", "156", "155", "147", "166", "GT", "GTV", "Brera", "Spider", "4C", "166"],
  Alpine: ["A110", "A290"],
  "Aston Martin": ["Vantage", "DB7", "DB9", "DB11", "DB12", "DBS", "DBX", "Rapide", "Vanquish", "Virage"],
  Audi: ["A1", "A2", "A3", "A4", "A4 Allroad", "A5", "A6", "A6 Allroad", "A7", "A8", "S1", "S3", "S4", "S5", "S6", "S7", "S8", "RS3", "RS4", "RS5", "RS6", "RS7", "Q2", "Q3", "Q4 e-tron", "Q5", "Q7", "Q8", "SQ5", "e-tron", "e-tron GT", "TT", "TTS", "TT RS", "R8", "80", "100", "Cabriolet"],
  Bentley: ["Continental", "Continental GT", "Flying Spur", "Bentayga", "Arnage", "Mulsanne", "Azure"],
  BMW: ["1 Series", "2 Series", "2 Series Active Tourer", "3 Series", "3 Series GT", "4 Series", "4 Series Gran Coupé", "5 Series", "5 Series GT", "6 Series", "6 Series Gran Coupé", "7 Series", "8 Series", "X1", "X2", "X3", "X4", "X5", "X6", "X7", "Z3", "Z4", "i3", "i4", "i5", "i7", "i8", "iX", "iX1", "iX2", "iX3", "M2", "M3", "M4", "M5", "M6", "M8", "X3 M", "X5 M", "X6 M"],
  BYD: ["Atto 3", "Dolphin", "Seal", "Seal U", "Han", "Tang", "Song", "Seagull"],
  Cadillac: ["CTS", "ATS", "STS", "BLS", "SRX", "XT4", "XT5", "Escalade", "Lyriq"],
  Chevrolet: ["Spark", "Aveo", "Cruze", "Lacetti", "Captiva", "Camaro", "Corvette", "Niva", "Orlando", "Trax", "Tahoe", "Epica", "Volt"],
  Chrysler: ["300C", "300M", "Voyager", "Grand Voyager", "PT Cruiser", "Sebring", "Crossfire", "Pacifica"],
  Citroën: ["C1", "C2", "C3", "C3 Aircross", "C3 Picasso", "C4", "C4 Cactus", "C4 Picasso", "C4 SpaceTourer", "C5", "C5 Aircross", "C5 X", "C6", "C8", "C-Elysée", "Berlingo", "Jumpy", "SpaceTourer", "Xsara", "Xsara Picasso", "Saxo", "Nemo", "DS3", "DS4", "DS5"],
  Cupra: ["Leon", "Formentor", "Born", "Ateca", "Tavascan", "Terramar"],
  Dacia: ["Sandero", "Sandero Stepway", "Logan", "Logan MCV", "Duster", "Dokker", "Lodgy", "Jogger", "Spring"],
  Daewoo: ["Matiz", "Lanos", "Nexia", "Nubira", "Sens", "Leganza", "Tacuma", "Kalos", "Tico", "Espero"],
  Dodge: ["Caliber", "Journey", "Nitro", "Charger", "Challenger", "Avenger", "RAM"],
  DS: ["DS 3", "DS 3 Crossback", "DS 4", "DS 5", "DS 7", "DS 9"],
  Ferrari: ["Roma", "Portofino", "California", "296", "488", "458", "F8", "SF90", "812", "FF", "GTC4Lusso", "Purosangue"],
  Fiat: ["500", "500e", "500X", "500L", "Panda", "Punto", "Grande Punto", "Tipo", "Bravo", "Brava", "Stilo", "Doblo", "Qubo", "Croma", "Sedici", "Freemont", "Multipla", "Ducato", "Fiorino", "Talento"],
  Ford: ["Ka", "Ka+", "Fiesta", "Focus", "Mondeo", "Fusion", "Puma", "EcoSport", "Kuga", "Edge", "Explorer", "Mustang", "Mustang Mach-E", "B-Max", "C-Max", "S-Max", "Galaxy", "Tourneo", "Transit", "Transit Custom", "Transit Connect", "Ranger", "Escort", "Cougar"],
  Genesis: ["G70", "G80", "G90", "GV60", "GV70", "GV80"],
  Honda: ["Jazz", "Civic", "Civic Type R", "Accord", "CR-V", "HR-V", "CR-Z", "Insight", "FR-V", "Legend", "Stream", "S2000", "e", "ZR-V"],
  Hyundai: ["i10", "i20", "i30", "i40", "ix20", "ix35", "Accent", "Getz", "Elantra", "Sonata", "Coupe", "Matrix", "Tucson", "Santa Fe", "Kona", "Bayon", "Ioniq", "Ioniq 5", "Ioniq 6", "Nexo"],
  Infiniti: ["Q30", "Q50", "Q60", "Q70", "QX30", "QX50", "QX70", "FX", "EX", "G37"],
  Jaguar: ["XE", "XF", "XJ", "XK", "S-Type", "X-Type", "F-Type", "E-Pace", "F-Pace", "I-Pace"],
  Jeep: ["Renegade", "Compass", "Cherokee", "Grand Cherokee", "Wrangler", "Avenger", "Patriot", "Commander", "Wagoneer"],
  Kia: ["Picanto", "Rio", "Ceed", "Cee'd", "ProCeed", "Optima", "Magentis", "Stinger", "Stonic", "Venga", "Soul", "Niro", "Sportage", "Sorento", "Carens", "Carnival", "XCeed", "EV6", "EV9"],
  Lada: ["Niva", "Niva Travel", "Vesta", "Granta", "Kalina", "Priora", "Largus", "Samara", "XRAY", "2104", "2105", "2106", "2107", "2109", "2110", "2114", "2115"],
  Lamborghini: ["Huracán", "Aventador", "Urus", "Gallardo", "Murciélago", "Revuelto"],
  Lancia: ["Ypsilon", "Delta", "Musa", "Thesis", "Thema", "Phedra", "Lybra"],
  "Land Rover": ["Defender", "Discovery", "Discovery Sport", "Range Rover", "Range Rover Sport", "Range Rover Evoque", "Range Rover Velar", "Freelander"],
  Lexus: ["CT", "IS", "ES", "GS", "LS", "UX", "NX", "RX", "RZ", "RC", "LC", "GX", "LX", "RX L"],
  Lotus: ["Elise", "Exige", "Evora", "Emira", "Eletre", "Esprit"],
  Maserati: ["Ghibli", "Quattroporte", "Levante", "Grecale", "GranTurismo", "GranCabrio", "MC20", "Coupé", "Spyder"],
  Mazda: ["2", "3", "5", "6", "CX-3", "CX-30", "CX-5", "CX-7", "CX-60", "CX-80", "MX-5", "MX-30", "RX-8", "323", "626", "Premacy"],
  McLaren: ["540C", "570S", "600LT", "620R", "650S", "720S", "765LT", "GT", "Artura", "MP4-12C"],
  Mercedes: ["A-Class", "B-Class", "C-Class", "E-Class", "S-Class", "CLA", "CLS", "CLK", "GLA", "GLB", "GLC", "GLE", "GLK", "GLS", "G-Class", "ML", "GL", "R-Class", "SL", "SLK", "SLC", "SLS", "AMG GT", "CLE", "EQA", "EQB", "EQC", "EQE", "EQS", "EQV", "Citan", "V-Class", "Viano", "Vito", "Sprinter"],
  MG: ["MG3", "MG4", "MG5", "ZS", "HS", "EHS", "Marvel R", "Cyberster", "ZR", "TF"],
  Mini: ["One", "Cooper", "Cooper S", "Clubman", "Countryman", "Paceman", "Cabrio", "Coupé", "Roadster", "Electric"],
  Mitsubishi: ["Colt", "Lancer", "Lancer Evolution", "Carisma", "Galant", "ASX", "Outlander", "Eclipse Cross", "Pajero", "Pajero Sport", "Shogun", "L200", "Space Star", "Grandis", "i-MiEV"],
  Nissan: ["Micra", "Note", "Leaf", "Juke", "Qashqai", "Qashqai+2", "X-Trail", "Murano", "Pathfinder", "Navara", "Pulsar", "Almera", "Primera", "Tiida", "Cube", "Ariya", "350Z", "370Z", "GT-R"],
  Opel: ["Corsa", "Astra", "Insignia", "Vectra", "Adam", "Karl", "Agila", "Meriva", "Zafira", "Mokka", "Crossland", "Grandland", "Antara", "Combo", "Vivaro", "Tigra", "Signum", "Cascada"],
  Peugeot: ["106", "107", "108", "206", "207", "208", "2008", "306", "307", "308", "3008", "408", "407", "508", "5008", "4007", "4008", "607", "806", "807", "1007", "Partner", "Rifter", "Expert", "Traveller", "Boxer", "RCZ"],
  Polestar: ["1", "2", "3", "4"],
  Porsche: ["911", "718 Cayman", "718 Boxster", "Cayman", "Boxster", "Panamera", "Macan", "Cayenne", "Taycan", "924", "928", "944", "968"],
  Renault: ["Twingo", "Clio", "Megane", "Megane E-Tech", "Scenic", "Grand Scenic", "Captur", "Kadjar", "Arkana", "Austral", "Koleos", "Talisman", "Laguna", "Fluence", "Latitude", "Espace", "Modus", "Wind", "Zoe", "Kangoo", "Trafic", "Master"],
  "Rolls-Royce": ["Ghost", "Phantom", "Wraith", "Dawn", "Cullinan", "Spectre", "Silver Shadow"],
  Saab: ["9-3", "9-5", "9-2X", "9-4X", "900", "9000"],
  Seat: ["Mii", "Ibiza", "Cordoba", "Leon", "Toledo", "Exeo", "Altea", "Altea XL", "Arosa", "Arona", "Ateca", "Tarraco", "Alhambra"],
  Škoda: ["Citigo", "Fabia", "Rapid", "Scala", "Octavia", "Superb", "Roomster", "Praktik", "Yeti", "Kamiq", "Karoq", "Kodiaq", "Enyaq", "Felicia", "Favorit"],
  Smart: ["ForTwo", "ForFour", "Roadster", "Crossblade", "#1", "#3"],
  SsangYong: ["Tivoli", "Korando", "Rexton", "Musso", "Actyon", "Kyron", "Rodius", "XLV", "Torres"],
  Subaru: ["Impreza", "WRX", "Legacy", "Outback", "Forester", "XV", "Crosstrek", "Levorg", "BRZ", "Tribeca", "Justy", "Solterra"],
  Suzuki: ["Celerio", "Alto", "Swift", "Baleno", "Ignis", "Splash", "SX4", "S-Cross", "Vitara", "Grand Vitara", "Jimny", "Liana", "Kizashi", "Across", "Swace"],
  Tesla: ["Model 3", "Model Y", "Model S", "Model X", "Cybertruck", "Roadster"],
  Toyota: ["Aygo", "Aygo X", "Yaris", "Yaris Cross", "Corolla", "Corolla Cross", "Auris", "Camry", "Avensis", "Verso", "C-HR", "RAV4", "Highlander", "Land Cruiser", "Prius", "bZ4X", "Supra", "GT86", "GR86", "Celica", "MR2", "Hilux", "Proace", "Avensis Verso"],
  VW: ["Up", "Fox", "Lupo", "Polo", "Golf", "Golf Plus", "Golf Sportsvan", "Jetta", "Bora", "Vento", "Passat", "Passat CC", "CC", "Arteon", "Eos", "Beetle", "New Beetle", "Scirocco", "Corrado", "T-Cross", "T-Roc", "Taigo", "Tiguan", "Tiguan Allspace", "Touareg", "Touran", "Sharan", "Caddy", "Transporter", "Multivan", "Amarok", "ID.3", "ID.4", "ID.5", "ID.7", "ID.Buzz"],
  Volvo: ["C30", "S40", "V40", "V50", "S60", "V60", "S70", "V70", "S80", "S90", "V90", "C40", "C70", "XC40", "XC60", "XC70", "XC90", "EX30", "EX90", "440", "460", "850", "940", "960"],
  ZAZ: ["Lanos", "Sens", "Vida", "Forza", "Chance", "Slavuta", "Tavria", "1102", "966", "968"],
};

export function getModelsForBrand(brand: string | undefined): string[] {
  if (!brand) return [];
  return MODELS_BY_BRAND[brand] ?? [];
}

/** True if listing.model belongs to the picked base model (startsWith match). */
export function listingMatchesModel(listingModel: string, modelFilter: string): boolean {
  return listingModel.toLowerCase().startsWith(modelFilter.toLowerCase());
}
