/**
 * Brand → base-model dictionary for catalog filters and listing forms.
 *
 * Listings store specific trim names like "X5 xDrive30d" or "320d F30".
 * Filtering uses startsWith() against the base model, so picking "X5" matches
 * "X5 xDrive30d", "X5 M50i", etc.
 *
 * Spellings of pre-existing brands ("VW", "Mercedes", "Škoda", "Citroën")
 * are kept as-is so older listings and saved filters keep matching.
 */

export const BRANDS: string[] = [
  "Abarth",
  "Alfa Romeo",
  "Alpine",
  "Aston Martin",
  "Audi",
  "Bentley",
  "BMW",
  "BYD",
  "Cadillac",
  "Chevrolet",
  "Chrysler",
  "Citroën",
  "Cupra",
  "Dacia",
  "Daewoo",
  "Dodge",
  "DS",
  "Ferrari",
  "Fiat",
  "Ford",
  "Genesis",
  "Honda",
  "Hyundai",
  "Infiniti",
  "Jaguar",
  "Jeep",
  "Kia",
  "Lada",
  "Lamborghini",
  "Lancia",
  "Land Rover",
  "Lexus",
  "Lotus",
  "Maserati",
  "Mazda",
  "McLaren",
  "Mercedes",
  "MG",
  "Mini",
  "Mitsubishi",
  "Nissan",
  "Opel",
  "Peugeot",
  "Polestar",
  "Porsche",
  "Renault",
  "Rolls-Royce",
  "Saab",
  "Seat",
  "Škoda",
  "Smart",
  "SsangYong",
  "Subaru",
  "Suzuki",
  "Tesla",
  "Toyota",
  "VW",
  "Volvo",
  "ZAZ",
];

export const MODELS_BY_BRAND: Record<string, string[]> = {
  Abarth: ["500", "595", "695", "124 Spider"],
  "Alfa Romeo": ["MiTo", "Giulietta", "Giulia", "Stelvio", "Tonale", "159", "156", "147", "Brera", "GT"],
  Alpine: ["A110"],
  "Aston Martin": ["Vantage", "DB11", "DB12", "DBS", "DBX", "Rapide"],
  Audi: ["A1", "A3", "A4", "A5", "A6", "A7", "A8", "Q2", "Q3", "Q4 e-tron", "Q5", "Q7", "Q8", "e-tron", "e-tron GT", "TT", "R8", "RS3", "RS4", "RS6"],
  Bentley: ["Continental", "Flying Spur", "Bentayga"],
  BMW: ["1 Series", "2 Series", "3 Series", "4 Series", "5 Series", "6 Series", "7 Series", "8 Series", "X1", "X2", "X3", "X4", "X5", "X6", "X7", "Z4", "i3", "i4", "i5", "i7", "iX", "iX3", "M2", "M3", "M4", "M5"],
  BYD: ["Atto 3", "Dolphin", "Seal", "Han", "Tang"],
  Cadillac: ["CTS", "ATS", "Escalade", "XT5", "SRX", "BLS"],
  Chevrolet: ["Spark", "Aveo", "Cruze", "Lacetti", "Captiva", "Camaro", "Niva", "Orlando"],
  Chrysler: ["300C", "Voyager", "PT Cruiser", "Sebring"],
  Citroën: ["C1", "C2", "C3", "C3 Aircross", "C4", "C4 Cactus", "C5", "C5 Aircross", "C5 X", "Berlingo", "Jumpy", "Xsara", "Picasso"],
  Cupra: ["Leon", "Formentor", "Born", "Ateca", "Tavascan"],
  Dacia: ["Sandero", "Logan", "Duster", "Dokker", "Lodgy", "Jogger", "Spring"],
  Daewoo: ["Matiz", "Lanos", "Nexia", "Nubira", "Sens"],
  Dodge: ["Caliber", "Journey", "Nitro", "Charger", "Challenger"],
  DS: ["DS 3", "DS 4", "DS 7", "DS 9"],
  Ferrari: ["Roma", "Portofino", "296", "488", "F8", "SF90", "812"],
  Fiat: ["500", "500X", "500L", "Panda", "Punto", "Tipo", "Bravo", "Doblo", "Croma", "Ducato"],
  Ford: ["Ka", "Fiesta", "Focus", "Mondeo", "Fusion", "Puma", "EcoSport", "Kuga", "Edge", "Explorer", "Mustang", "Mustang Mach-E", "C-Max", "S-Max", "Galaxy", "Transit", "Ranger"],
  Genesis: ["G70", "G80", "G90", "GV70", "GV80"],
  Honda: ["Jazz", "Civic", "Accord", "CR-V", "HR-V", "CR-Z", "Insight", "e"],
  Hyundai: ["i10", "i20", "i30", "i40", "Accent", "Elantra", "Sonata", "Tucson", "Santa Fe", "Kona", "Ioniq", "Ioniq 5", "Ioniq 6"],
  Infiniti: ["Q30", "Q50", "Q70", "QX30", "QX50", "QX70"],
  Jaguar: ["XE", "XF", "XJ", "F-Type", "E-Pace", "F-Pace", "I-Pace"],
  Jeep: ["Renegade", "Compass", "Cherokee", "Grand Cherokee", "Wrangler", "Avenger"],
  Kia: ["Picanto", "Rio", "Ceed", "Optima", "Stinger", "Stonic", "Sportage", "Sorento", "Niro", "Soul", "ProCeed", "EV6"],
  Lada: ["Niva", "Vesta", "Granta", "Kalina", "Priora", "Largus", "Samara", "2107"],
  Lamborghini: ["Huracán", "Aventador", "Urus", "Gallardo"],
  Lancia: ["Ypsilon", "Delta", "Musa"],
  "Land Rover": ["Defender", "Discovery", "Discovery Sport", "Range Rover", "Range Rover Sport", "Range Rover Evoque", "Range Rover Velar", "Freelander"],
  Lexus: ["CT", "IS", "ES", "GS", "LS", "UX", "NX", "RX", "RZ", "LC"],
  Lotus: ["Elise", "Exige", "Evora", "Emira", "Eletre"],
  Maserati: ["Ghibli", "Quattroporte", "Levante", "Grecale", "GranTurismo", "MC20"],
  Mazda: ["2", "3", "6", "CX-3", "CX-30", "CX-5", "CX-60", "MX-5", "MX-30"],
  McLaren: ["570S", "720S", "GT", "Artura"],
  Mercedes: ["A-Class", "B-Class", "C-Class", "E-Class", "S-Class", "CLA", "CLS", "GLA", "GLB", "GLC", "GLE", "GLS", "G-Class", "SL", "SLK", "AMG GT", "EQA", "EQB", "EQC", "EQE", "EQS", "V-Class", "Vito", "Sprinter"],
  MG: ["MG3", "MG4", "MG5", "ZS", "HS", "Marvel R"],
  Mini: ["Cooper", "Clubman", "Countryman", "Paceman", "Cabrio"],
  Mitsubishi: ["Colt", "Lancer", "ASX", "Outlander", "Eclipse Cross", "Pajero", "L200", "Space Star"],
  Nissan: ["Micra", "Note", "Leaf", "Juke", "Qashqai", "X-Trail", "Murano", "Navara", "Pulsar", "Ariya", "370Z", "GT-R"],
  Opel: ["Corsa", "Astra", "Insignia", "Adam", "Karl", "Meriva", "Zafira", "Mokka", "Crossland", "Grandland", "Combo", "Vivaro"],
  Peugeot: ["108", "208", "2008", "308", "3008", "408", "508", "5008", "Partner", "Rifter", "RCZ"],
  Polestar: ["1", "2", "3", "4"],
  Porsche: ["911", "718 Cayman", "718 Boxster", "Panamera", "Macan", "Cayenne", "Taycan"],
  Renault: ["Twingo", "Clio", "Megane", "Megane E-Tech", "Scenic", "Captur", "Kadjar", "Arkana", "Koleos", "Talisman", "Laguna", "Espace", "Zoe", "Kangoo", "Trafic", "Master"],
  "Rolls-Royce": ["Ghost", "Phantom", "Wraith", "Cullinan"],
  Saab: ["9-3", "9-5"],
  Seat: ["Mii", "Ibiza", "Leon", "Toledo", "Altea", "Arosa", "Arona", "Ateca", "Tarraco", "Alhambra"],
  Škoda: ["Citigo", "Fabia", "Rapid", "Scala", "Octavia", "Superb", "Roomster", "Yeti", "Kamiq", "Karoq", "Kodiaq", "Enyaq"],
  Smart: ["ForTwo", "ForFour", "Roadster", "#1", "#3"],
  SsangYong: ["Tivoli", "Korando", "Rexton", "Musso", "Actyon"],
  Subaru: ["Impreza", "Legacy", "Outback", "Forester", "XV", "Levorg", "BRZ"],
  Suzuki: ["Celerio", "Swift", "Baleno", "Ignis", "SX4", "S-Cross", "Vitara", "Jimny"],
  Tesla: ["Model 3", "Model Y", "Model S", "Model X", "Cybertruck", "Roadster"],
  Toyota: ["Aygo", "Yaris", "Corolla", "Auris", "Camry", "Avensis", "C-HR", "RAV4", "Highlander", "Land Cruiser", "Prius", "bZ4X", "Supra", "GT86", "Hilux", "Proace"],
  VW: ["Up", "Polo", "Golf", "Jetta", "Passat", "Arteon", "Beetle", "Scirocco", "T-Cross", "T-Roc", "Taigo", "Tiguan", "Touareg", "Touran", "Sharan", "Caddy", "Transporter", "ID.3", "ID.4", "ID.5", "ID.7", "ID.Buzz"],
  Volvo: ["S60", "S90", "V40", "V60", "V90", "XC40", "XC60", "XC90", "C40", "EX30", "EX90"],
  ZAZ: ["Lanos", "Sens", "Vida", "Forza", "Chance", "Slavuta"],
};

export function getModelsForBrand(brand: string | undefined): string[] {
  if (!brand) return [];
  return MODELS_BY_BRAND[brand] ?? [];
}

/** True if listing.model belongs to the picked base model (startsWith match). */
export function listingMatchesModel(listingModel: string, modelFilter: string): boolean {
  return listingModel.toLowerCase().startsWith(modelFilter.toLowerCase());
}
